### ISSUE TITLE
Reporting Bug: Angular - Error Print with SVG Logo in Survey

### ISSUE THREAD

**Issue by the-ft** [surveyjs/survey-pdf#190]
I just tried surveyjs in angular

adding a logo, which is svg ("data:image/svg+xml;base64,...."), i get an error when i try to use **savePdf()**
png or jpg images working fine ("data:image/png;base64,..)

`ERROR Error: addImage does not support files of type 'UNKNOWN', please ensure that a plugin for 'UNKNOWN' support is added.`
`    P jspdf.es.min.js:86`
`    addImage jspdf.es.min.js:86`
`    DrillForContent survey.pdf.js:10544`
`    process survey.pdf.js:10840`
`    done survey.pdf.js:10692`
`    onload survey.pdf.js:10718`

here is an [codesandbox](https://codesandbox.io/s/surveyjs-angular-pdf-testing-sfbvqv), i modified your code example
(check json.ts for survey content)

punch the top button, and you get the error in the console

**Comment by JaneSjs** [comment]
Hello @the-ft,
Thank you for contacting us. The exception occurs due to tje `jspdf` library unable to process the provided images. You can enable the [applyImageFit](https://surveyjs.io/pdf-generator/documentation/api-reference/idocoptions#applyImageFit) option to fix the issue.
```let options = {
    applyImageFit: true,
    fontSize: 14,
    margins: {
      left: 10,
      right: 10,
      top: 10,
      bot: 10
    },

    format: [pdfWidth, pdfHeight]
  };
  const surveyPDF = new SurveyPDF(json, options);
```
The updated example is available at https://codesandbox.io/s/surveyjs-angular-pdf-testing-forked-zvn6op?file=/src/app/components/pdf.component.ts:512-744.

We'll research the issue and check if it's possible to somehow handle it in our PDF Export library. We'll post updates if we have any news to share.

Thank you

**Comment by the-ft** [comment]
thnx for the fast reply.
signing field, set to svg, has the same prob ("dataFormat": "image/svg+xml"), and fixed by applyImageFit too.
you should set it by default true (survey.pdf.js:1814), or add it in your code examples. 
hey.. it fixed also a ratio prob. 

does it have any downsides ( a not really significant lower image quality isnt relevant for me. my focus is more on smaller file size)?

**Comment by JaneSjs** [comment]
Hi @the-ft,
Thank you for the update. We will check if we can handle this issue in our code. Thank you. 

Regarding the `applyImageFit` option: it fixes the issue because when it's enabled, an image is internally converted to an appropriate format. I'm not sure I get your point about a smaller file size. Please elaborate on it.
