### ISSUE TITLE
Ability to change font size of PDF responses

### ISSUE THREAD

**Issue by cxm6467** [surveyjs/survey-pdf#27]
Is there a way to customize the font size for survey responses?

**Comment by gologames** [comment]
Hello,

According to [SurveyPDF options documentation](https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-export#content-docs) you can pass `fontSize` parameter via options. Something like below:
```javascript
var options = {
	fontSize: 14
};
var survey = new SurveyPDF.SurveyPDF(json, options);
```

You can also look at SurveyCreator with SurveyPDF integration example. Choose a survey in property grid selector, go to PDF section and set `Pdf Font Size` property

![image](https://user-images.githubusercontent.com/30930391/94270219-69719100-ff48-11ea-9fde-580e0dde0822.png)

Then go to `Test Survey` tab and click `Save PDF` button to export the survey to PDF

![image](https://user-images.githubusercontent.com/30930391/94270313-8908b980-ff48-11ea-9e98-b7562d07bc9b.png)


Thanks, Alex
SurveyJS Team

**Comment by cxm6467** [comment]
@gologames I apologize for not being more specific as it was a late night post.  Am I correct that the Pdf Font Size attribute is for the question text and not the response itself?

For example, if "question1" is of the comment type, is there a way when exporting the pdf to scale the comment box and font in it?  In our implementation, the responses can be quite long for comments rendering them unreadable.

**Comment by gologames** [comment]
Hello,

The `fontSize` option (and `Pdf Font Size` attribute as well) affects both on question's title and answer. But if your survey's `mode` had set to `edit` then PDF will be exported in interactive mode and text will fit available area (this internal behavior of PDF document's forms)
![image](https://user-images.githubusercontent.com/30930391/94340584-b4a0a800-000b-11eb-94ed-9af81a286258.png)

 Otherwise if you set `mode` to `display` then SurveyPDF library automatically enlarge response field to required size
![image](https://user-images.githubusercontent.com/30930391/94340641-17923f00-000c-11eb-83a0-92d6cae6c869.png)

Does this is good enough for you?

Thanks, Alex
SurveyJS Team

**Comment by cxm6467** [comment]
@gologames this solves it! Thank you so much. The survey data we had didn’t wasn’t set to read only before exporting.
