### ISSUE TITLE
Not working when <br> or <br/> found in html element

### ISSUE THREAD

**Issue by vicsanca** [surveyjs/survey-pdf#32]
Gives an error in console. We are working around this replacing brs before printing from json.

**Comment by andrewtelnov** [comment]
@vicsanca Here is [the working example](https://plnkr.co/edit/4fiFEpaT9cKnNQMT).

Thank you,
Andrew

**Comment by gologames** [comment]
Hello,

Unfortunately, as described in our [HTML to PDF article](https://surveyjs.io/Documentation/Pdf-Export?id=HtmlToPdf), it is difficult to render HTML inside PDF document due to there is no browser inside PDF document. You can try to render HTML as image via our API or use your workaround with removing `<br>` tags

Thanks, Alex
SurveyJS Team
