### ISSUE TITLE
Using <br><br> in an element of type html crashes the PDF generation

### ISSUE THREAD

**Issue by JauresC** [surveyjs/survey-pdf#326]
When i use multiple `<br><br>` in an element of type HTML, the generation of the PDF will fail.

Here's a simple exemple showing the bug :
https://plnkr.co/edit/HDXSf31SNTLwsCCn

**Comment by JaneSjs** [comment]
Hello @JauresC,
It's a known issue caused by the way the jsPDF library processes a duplicated <br> tag. Unfortunately, `</br></br>` tags are not supported by the jsPDF's `from_html` method. Please either remove an extra `<br>` tag or use the [image HTML rendering option (`htmlRenderAs: "image"`)](https://surveyjs.io/pdf-generator/documentation/customize-survey-question-rendering-in-pdf-form#html-rendering).
