### ISSUE TITLE
Printing dates in user's locale

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-pdf#33]
Before opening another bug/question. For printing dates in user's locale we have to put some variable before generating? dates always are shown in US format. Still searching if is some problem in our side

_Originally posted by @vicsanca in https://github.com/surveyjs/survey-pdf/issues/31#issuecomment-732060225_

**Comment by vicsanca** [comment]
An example: https://plnkr.co/edit/BeDBcFBtDNS9g6sK
The problem is that date is shown with browser locale for dates, that is very useful. But when printing to pdf uses only text result.
Here in spain you see/input 31/12/2020, stores 2020-12-30 and prints 2020-12-30. Don't users browser's locale or survey locale.

Thanks again.

**Comment by gologames** [comment]
Hello,

This behavior of date input is specified by HTML5 standard. Here is the similar [ticket in our support](https://surveyjs.answerdesk.io/ticket/details/t5138/adorner-to-reformat-the-date-to-european-dd-mm-yyyy-format) with detailed explanation and workaround

Thanks, Alex
SurveyJS Team
